[build]
  base = "/"
  command = "yarn build"
  publish = "build"

[[plugins]]
  package = "@netlify/plugin-svelte"
  [plugins.inputs]
    command = "yarn build"

[build.environment]
  NODE_VERSION = "16"


